[package]
name = "eg"
version = "0.1.0"
edition = "2021"

[dependencies]
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
itertools = { workspace = true }
rand = { workspace = true }

clap = { version = "3.0", features = ["derive"] }

automata-core = { path = "../../automata-core" }
automata = { path = "../../automata" }
