#!/usr/bin/env bash
set -e

cargo fmt --check --all
echo "cargo fmt --check --all passed"
cargo clippy -- -D warnings
echo "cargo clippy --all -- -D warnings passed"
cargo doc --no-deps
echo "doc tests passed"
cargo test --all
echo "cargo test --all passed"
